- hosts: node1
  gather_facts: no
  tasks:
    - name: remove user pahani
      user: name=phani state=absent remove=yes
    - name: create multiple users
      user: name={{ item }} password={{ password }} state=present group=wheel 
      with_items:
        - ramesh
        - suresh
        - rakesh
