- hosts: aws
  remote_user: ec2-user
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
    - name: execute a shell
      shell: uptime
      register: result
    - debug: msg={{ result }}
