- hosts: node1
  user: root
  connection: ssh
  gather_facts: no
  tasks:
    - name: istall wget on node1 group
      yum: pkg=wgeghjt state=installed
      ignore_errors: yes
    - name: install httpd
      yum: pkg=httpd state=installed
