--- # includes
- hosts: node1
  user: root
  connection: ssh
  gather_facts: no
  tasks:
    - include: packages/packages.yml
    - include: commands/commands.yml

  handlers:
    - include: handler/handler.yml


