- hosts: aws
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
    - name: gather facts
      ec2_facts:
    - name: condition 
      debug: msg='{{ ansible_ec2_instance_type }}'
