- hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
    - name: gather all ec2 facts
      ec2_remote_facts:
        region: us-east-2
      register: remote_facts
    - debug: msg={{remote_facts}}
