- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - files/awscredentials.yml
  tasks:
    - name: launch ec2
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: us-east-2
        image: ami-cfdafaaa
        instance_type: t2.micro
        count: 2
        assign_public_ip: yes
    
