--- # myfirst play book
- hosts: server
  become_method: root
  sudo: yes
  gather_facts: no
  tasks:
  - name: install httpd
    yum: pkg=httpd state=installed
  - name: waiting for httpd to start
    wait_for:
      port: 80
      state: started 
  - name: verify for wget
    action: yum name=wget state=present
